const products = [
  {
    _id: '1',
    name: 'Jabuke',
    image: '/images/jabuke.jpg',
    description: 'Sveže domaće jabuke sorte Idared, slatko-kiselkastog ukusa. Idealne za jelo i kolače.',
    category: 'Voće',
    price: 120.0,
    countInStock: 50,
    rating: 4.5,
    numReviews: 18,
  },
  {
    _id: '2',
    name: 'Banane',
    image: '/images/banane.jpg',
    description: 'Zrele banane, bogate kalijumom. Savršene za užinu i smutije.',
    category: 'Voće',
    price: 170.0,
    countInStock: 40,
    rating: 4.0,
    numReviews: 9,
  },
  {
    _id: '3',
    name: 'Narandže',
    image: '/images/narandze.jpg',
    description: 'Sočne narandže bogate vitaminom C. Idealne za ceđenje soka i svakodnevnu konzumaciju.',
    category: 'Voće',
    price: 210.0,
    countInStock: 30,
    rating: 5.0,
    numReviews: 22,
  },
  {
    _id: '4',
    name: 'Breskve',
    image: '/images/breskve.jpg',
    description: 'Slatke i mirisne breskve sa sočnim mesom. Savršene za osveženje tokom leta.',
    category: 'Voće',
    price: 190.0,
    countInStock: 60,
    rating: 4.2,
    numReviews: 7,
  },
  {
    _id: '5',
    name: 'Kruške',
    image: '/images/kruska.jpg',
    description: 'Sveže kruške blagog i slatkog ukusa. Odličan izbor za zdravu užinu.',
    category: 'Voće',
    price: 250.0,
    countInStock: 0,
    rating: 4.8,
    numReviews: 31,
  },
  {
    _id: '6',
    name: 'Šljive',
    image: '/images/sljive.jpg',
    description: 'Domaće šljive bogatog ukusa. Idealne za jelo, kolače i pripremu džema.',
    category: 'Voće',
    price: 120.0,
    countInStock: 35,
    rating: 4.3,
    numReviews: 5,
  },
  {
    _id: '7',
    name: 'Trešnje',
    image: '/images/tresnje.jpg',
    description: 'Sočne trešnje tamnocrvene boje i slatkog ukusa. Omiljeno sezonsko voće.',
    category: 'Voće',
    price: 270.0,
    countInStock: 45,
    rating: 4.6,
    numReviews: 14,
  },
  {
    _id: '8',
    name: 'Jagode',
    image: '/images/jagoda.jpg',
    description: 'Mirisne jagode pune prirodne slatkoće. Savršene za deserte i voćne salate.',
    category: 'Voće',
    price: 220.0,
    countInStock: 25,
    rating: 4.7,
    numReviews: 10,
  },
  {
    _id: '9',
    name: 'Lubenice',
    image: '/images/lubenica.jpg',
    description: 'Osvežavajuća lubenica sa sočnim crvenim plodom. Idealna za vrele letnje dane.',
    category: 'Voće',
    price: 90.0,
    countInStock: 200,
    rating: 5.0,
    numReviews: 13,
  },
  {
    _id: '10',
    name: 'Dinje',
    image: '/images/dinja.jpg',
    description: 'Slatka i aromatična dinja bogata vitaminima. Odlična za osveženje i voćne salate.',
    category: 'Voće',
    price: 220.0,
    countInStock: 27,
    rating: 4.2,
    numReviews: 9,
  },
  {
    _id: '11',
    name: 'Limun',
    image: '/images/limun.jpg',
    description: 'Svež limun intenzivnog ukusa i mirisa. Neizostavan dodatak napicima i jelima.',
    category: 'Voće',
    price: 300.0,
    countInStock: 18,
    rating: 4.4,
    numReviews: 7,
  },
  {
    _id: '12',
    name: 'Ananas',
    image: '/images/ananas.jpg',
    description: 'Egzotični ananas sočnog i osvežavajućeg ukusa. Bogat vitaminima i mineralima.',
    category: 'Voće',
    price: 270.0,
    countInStock: 20,
    rating: 4.1,
    numReviews: 11,
  },
  {
    _id: '13',
    name: 'Kivi',
    image: '/images/kivi.jpg',
    description: 'Kivi bogat vitaminom C i vlaknima. Osvežavajućeg ukusa i mekane teksture.',
    category: 'Voće',
    price: 350.0,
    countInStock: 23,
    rating: 4.0,
    numReviews: 9,
  },
  {
    _id: '14',
    name: 'Grožđe',
    image: '/images/grozdje.jpg',
    description: 'Sveže grožđe slatkog ukusa, idealno za užinu ili pripremu voćnih salata.',
    category: 'Voće',
    price: 480.0,
    countInStock: 22,
    rating: 4.7,
    numReviews: 11,
  },
  {
    _id: '15',
    name: 'Paprika',
    image: '/images/paprika.jpg',
    description: 'Mesnata paprika bogata vitaminima. Odlična za salate, pečenje i punjenje.',
    category: 'Povrće',
    price: 420.0,
    countInStock: 17,
    rating: 5.0,
    numReviews: 7,
  },
  {
    _id: '16',
    name: 'Krastavac',
    image: '/images/krastavac.jpg',
    description: 'Svež i hrskav krastavac, savršen dodatak salatama i laganim obrocima.',
    category: 'Povrće',
    price: 110.0,
    countInStock: 22,
    rating: 4.7,
    numReviews: 8,
  },
  {
    _id: '17',
    name: 'Krompir',
    image: '/images/krompir.jpg',
    description: 'Kvalitetan domaći krompir pogodan za kuvanje, pečenje i prženje.',
    category: 'Povrće',
    price: 90.0,
    countInStock: 60,
    rating: 4.5,
    numReviews: 17,
  },
  {
    _id: '18',
    name: 'Karfiol',
    image: '/images/karfiol.jpg',
    description: 'Svež karfiol blagog ukusa. Idealan za čorbe, priloge i gratinirana jela.',
    category: 'Povrće',
    price: 260.0,
    countInStock: 30,
    rating: 4.7,
    numReviews: 13,
  },
  {
    _id: '19',
    name: 'Šargarepa',
    image: '/images/sargarepa.jpg',
    description: 'Hrskava šargarepa bogata vitaminom A. Odlična za salate, supe i sokove.',
    category: 'Povrće',
    price: 80.0,
    countInStock: 40,
    rating: 5.0,
    numReviews: 15,
  },
  {
    _id: '20',
    name: 'Grašak',
    image: '/images/grasak.jpg',
    description: 'Mladi zeleni grašak prijatnog ukusa. Savršen za variva i priloge.',
    category: 'Povrće',
    price: 170.0,
    countInStock: 15,
    rating: 4.2,
    numReviews: 11,
  },
  {
    _id: '21',
    name: 'Tikvice',
    image: '/images/tikvica.jpg',
    description: 'Sveže tikvice nežnog ukusa. Pogodne za pečenje, punjenje i pripremu čorbi.',
    category: 'Povrće',
    price: 110.0,
    countInStock: 23,
    rating: 4.7,
    numReviews: 10,
  },
  {
    _id: '22',
    name: 'Luk',
    image: '/images/luk.jpg',
    description: 'Domaći crni luk intenzivne arome. Neizostavan sastojak brojnih jela.',
    category: 'Povrće',
    price: 70.0,
    countInStock: 19,
    rating: 5.0,
    numReviews: 6,
  },
  {
    _id: '23',
    name: 'Pečurke',
    image: '/images/pecurke.jpg',
    description: 'Sveže pečurke blagog ukusa i prijatne teksture. Odlične za razna jela.',
    category: 'Povrće',
    price: 420.0,
    countInStock: 25,
    rating: 4.6,
    numReviews: 9,
  },
  {
    _id: '24',
    name: 'Kupus',
    image: '/images/kupus.jpg',
    description: 'Svež kupus bogat vlaknima. Idealan za salate, kuvanje i kiseljenje.',
    category: 'Povrće',
    price: 80.0,
    countInStock: 20,
    rating: 4.7,
    numReviews: 7,
  },
  {
    _id: '25',
    name: 'Paradajz',
    image: '/images/paradajz.jpg',
    description: 'Sočan paradajz bogat ukusom. Savršen za salate, sosove i sendviče.',
    category: 'Povrće',
    price: 250.0,
    countInStock: 34,
    rating: 4.7,
    numReviews: 11,
  },
  {
    _id: '26',
    name: 'Španać',
    image: '/images/spanac.jpg',
    description: 'Svež španać bogat gvožđem i vitaminima. Odličan za pite, čorbe i priloge.',
    category: 'Povrće',
    price: 300.0,
    countInStock: 4,
    rating: 5.0,
    numReviews: 4,
  },
  {
    _id: '27',
    name: 'Rotkvica',
    image: '/images/rotkvica.jpg',
    description: 'Hrskava rotkvica blago ljutkastog ukusa. Idealan dodatak prolećnim salatama.',
    category: 'Povrće',
    price: 320.0,
    countInStock: 12,
    rating: 4.5,
    numReviews: 10,
  },
  {
    _id: '28',
    name: 'Brokoli',
    image: '/images/brokoli.jpg',
    description: 'Svež brokoli bogat vitaminima i mineralima. Odličan za kuvanje i pripremu zdravih obroka.',
    category: 'Povrće',
    price: 360.0,
    countInStock: 19,
    rating: 4.7,
    numReviews: 9,
  },
]

export default products